# Generated by Django 6.0.3 on 2026-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_movie_background_image_movie_poster_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
